BEGIN;

CREATE TABLE agecategories (
    id varchar(10) PRIMARY KEY,
    description varchar(30) NOT NULL,
    age_min integer NOT NULL,
    age_max integer NOT NULL,
    agonist smallint NOT NULL,
    out_category smallint NOT NULL DEFAULT 0
);

CREATE TABLE api_requests (
    id char(36) PRIMARY KEY,
    http_method varchar(10) NOT NULL,
    endpoint varchar(2048) NOT NULL,
    token varchar(2048),
    ip_address varchar(50) NOT NULL,
    request_data text,
    response_code integer NOT NULL,
    response_type varchar(50) DEFAULT 'json',
    response_data text,
    exception text,
    created timestamp NOT NULL,
    modified timestamp NOT NULL
);

CREATE TABLE athletes (
    id varchar(21) PRIMARY KEY,
    club_id varchar(21) NOT NULL,
    nome varchar(50) NOT NULL,
    cognome varchar(50),
    data_nascita varchar(20),
    sesso varchar(1),
    cod_fiscale varchar(20),
    federation_id smallint,
    n_tessera varchar(100),
    peso smallint,
    grado varchar(15),
    tesserino varchar(50),
    created_date timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_date timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE athlete_inscriptions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    athlete_id varchar(21) NOT NULL,
    categorycode_id varchar(10) NOT NULL,
    competition_id varchar(20) NOT NULL,
    cintura varchar(50) NOT NULL,
    n_iscrizione smallint,
    inviato smallint NOT NULL DEFAULT 0,
    modificato smallint NOT NULL DEFAULT 0,
    accorpamento smallint NOT NULL DEFAULT 0,
    deleted smallint NOT NULL DEFAULT 0,
    old_category varchar(15),
    created_date timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_date timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    final_ranking integer
);

CREATE TABLE categorycodes (
    id varchar(10) PRIMARY KEY,
    categoria varchar(50) NOT NULL,
    agecategory_id varchar(10),
    anno_min integer NOT NULL,
    anno_max integer NOT NULL,
    sesso text NOT NULL,
    grado varchar(300) NOT NULL,
    cat_peso varchar(10),
    peso_min integer,
    peso_max integer,
    specialita varchar(100) NOT NULL,
    costo_intero real NOT NULL,
    costo_scontato real NOT NULL,
    "codiceTipoCategorie" smallint NOT NULL,
    order_number integer NOT NULL,
    atleti_max integer
);

CREATE TABLE clubs (
    id varchar(21) PRIMARY KEY,
    club_code varchar(50),
    club_name varchar(500) NOT NULL,
    fiscal_code varchar(20) NOT NULL,
    short_name varchar(20),
    club_manager varchar(50) NOT NULL,
    telephone_n varchar(20) NOT NULL,
    mail varchar(100) NOT NULL,
    coach varchar(50) NOT NULL,
    last_login timestamp,
    created_date timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_date timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE club_inscriptions (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    club_id varchar(21) NOT NULL,
    competition_id varchar(20) NOT NULL,
    created_date timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE competitions (
    id varchar(20) PRIMARY KEY,
    responsabile varchar(100) NOT NULL,
    club_name varchar(100) NOT NULL,
    logo varchar(200),
    email varchar(200) NOT NULL,
    telephone varchar(50) NOT NULL,
    nome_gara varchar(500) NOT NULL,
    apertura_iscrizioni date,
    chiusura_iscrizioni date NOT NULL,
    data_gara date NOT NULL,
    locandina varchar(100),
    circolare varchar(100),
    nr_atleti integer NOT NULL,
    "codiceTipoCategorie" smallint,
    comp_status smallint NOT NULL DEFAULT 0,
    flag_tabs smallint NOT NULL DEFAULT 0,
    flag_classifications smallint NOT NULL DEFAULT 0,
    flag_timetable smallint NOT NULL DEFAULT 0
);

CREATE TABLE competition_club_rankings (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    competition_id varchar(50) NOT NULL,
    club_id varchar(50) NOT NULL,
    golds integer DEFAULT 0,
    silvers integer DEFAULT 0,
    bronzes integer DEFAULT 0,
    total_points integer DEFAULT 0,
    rank_position integer DEFAULT 0,
    created timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE federations (
    id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) NOT NULL
);

CREATE TABLE katas (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kata_name varchar(100)
);

CREATE TABLE logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "timestamp" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    registered_club varchar(50) NOT NULL,
    action text NOT NULL
);

CREATE TABLE rest_api_phinxlog (
    version bigint PRIMARY KEY,
    migration_name varchar(100),
    start_time timestamp,
    end_time timestamp,
    breakpoint smallint NOT NULL DEFAULT 0
);

CREATE TABLE results_judged_panel (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    athlete_inscription_id bigint NOT NULL,
    user_id varchar(10) NOT NULL,
    categorycode_id varchar(10) NOT NULL,
    round smallint NOT NULL DEFAULT 1,
    kata_id integer,
    referee_1 real, referee_2 real, referee_3 real, referee_4 real, referee_5 real,
    partial_score real,
    penalties_points real DEFAULT 0,
    total_score real,
    pool_ranking integer
);

CREATE TABLE results_match (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    categorycode_id varchar(10) NOT NULL,
    round integer NOT NULL,
    match_number integer NOT NULL,
    athlete_aka_inscription_id integer,
    athlete_ao_inscription_id integer,
    winner_inscription_id integer,
    loser_inscription_id integer,
    kata_id_aka integer,
    kata_id_ao integer,
    score_aka integer DEFAULT 0,
    score_ao integer DEFAULT 0,
    senshu_aka smallint DEFAULT 0,
    senshu_ao smallint DEFAULT 0,
    yuko_aka integer DEFAULT 0,
    yuko_ao integer DEFAULT 0,
    wazaari_aka integer DEFAULT 0,
    wazaari_ao integer DEFAULT 0,
    ippon_aka integer DEFAULT 0,
    ippon_ao integer DEFAULT 0,
    chui_1_aka smallint DEFAULT 0,
    chui_1_ao smallint DEFAULT 0,
    chui_2_aka smallint DEFAULT 0,
    chui_2_ao smallint DEFAULT 0,
    chui_3_aka smallint DEFAULT 0,
    chui_3_ao smallint DEFAULT 0,
    hans_chui_aka smallint DEFAULT 0,
    hans_chui_ao smallint DEFAULT 0,
    hans_aka smallint DEFAULT 0,
    hans_ao smallint DEFAULT 0,
    method_of_win varchar(15),
    is_bronze_final smallint NOT NULL DEFAULT 0
);

CREATE TABLE results_timed (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id varchar(10) NOT NULL,
    athlete_inscription_id integer NOT NULL,
    categorycode_id varchar(10) NOT NULL,
    minutes integer DEFAULT 0,
    seconds integer DEFAULT 0,
    milliseconds integer DEFAULT 0,
    penalties integer NOT NULL DEFAULT 0,
    total_time integer,
    pool_ranking integer
);

CREATE TABLE scores (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    athlete_inscription_id integer,
    user_id varchar(10),
    categorycode_id varchar(10),
    type varchar(5) DEFAULT 'E',
    n_prova integer,
    kata_id integer,
    opponentid numeric(10,0),
    referee_1 real, referee_2 real, referee_3 real, referee_4 real, referee_5 real,
    min real, max real, valid_1 real, valid_2 real, valid_3 real,
    total_without_penalties real,
    minutes integer, seconds integer, milliseconds integer, penalty integer,
    total_time varchar(50),
    total_time_seconds real,
    total real,
    senshu smallint DEFAULT 0,
    chui_1 smallint DEFAULT 0,
    chui_2 smallint DEFAULT 0,
    chui_3 smallint DEFAULT 0,
    hans_chui smallint DEFAULT 0,
    hansoku smallint DEFAULT 0,
    shikkaku smallint DEFAULT 0,
    ippon integer, yuko integer, wazaari integer,
    win smallint DEFAULT -1,
    color varchar(10),
    kiken smallint DEFAULT 0,
    cl_position integer,
    deleted smallint NOT NULL DEFAULT 0
);

CREATE TABLE scores_old (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    athlete_inscription_id integer,
    user_id smallint,
    category_code varchar(10),
    type varchar(5) DEFAULT 'E',
    n_prova integer,
    kata_id integer,
    opponentid numeric(10,0),
    referee_1_pt real, referee_2_pt real, referee_3_pt real, referee_4_pt real, referee_5_pt real,
    min_pt real, max_pt real, valid_1_pt real, valid_2_pt real, valid_3_pt real, total_pt real,
    referee_1_pa real, referee_2_pa real, referee_3_pa real, referee_4_pa real, referee_5_pa real,
    min_pa real, max_pa real, valid_1_pa real, valid_2_pa real, valid_3_pa real, total_pa real,
    minutes integer, seconds integer, milliseconds integer, penalty integer,
    total_time varchar(50),
    total_time_seconds real,
    total real,
    senshu smallint DEFAULT 0,
    "C1_CH" smallint DEFAULT 0,
    "C1_KK" smallint DEFAULT 0,
    "C1_HC" smallint DEFAULT 0,
    "C1_H" smallint DEFAULT 0,
    "C2_CH" smallint DEFAULT 0,
    "C2_KK" smallint DEFAULT 0,
    "C2_HC" smallint DEFAULT 0,
    "C2_H" smallint DEFAULT 0,
    ippon integer, yuko integer, wazaari integer,
    win smallint DEFAULT -1,
    color varchar(10),
    cl_position integer
);

CREATE TABLE sessions (
    id varchar(40) PRIMARY KEY DEFAULT '',
    data text,
    expires integer NOT NULL
);

CREATE TABLE statuses (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code varchar(20) NOT NULL,
    name varchar(20) NOT NULL,
    description varchar(200) NOT NULL,
    type varchar(15) NOT NULL
);

CREATE TABLE tatami_assignments (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id varchar(10) NOT NULL,
    categorycode_id varchar(10) NOT NULL,
    status varchar(20) NOT NULL,
    current_phase varchar(100) DEFAULT 'PENDING'
);

CREATE TABLE teams (
    id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    club_id varchar(21) NOT NULL,
    competition_id varchar(20) NOT NULL,
    componenti varchar(5000) NOT NULL,
    categoria varchar(100) NOT NULL,
    grado varchar(100) NOT NULL,
    created_date timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_date timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE users (
    id varchar(10) PRIMARY KEY,
    name varchar(30),
    username text NOT NULL,
    password text NOT NULL,
    email varchar(30),
    is_admin smallint NOT NULL DEFAULT 0
);

CREATE INDEX idx_athletes_club ON athletes (club_id);
CREATE INDEX idx_inscriptions_athlete ON athlete_inscriptions (athlete_id);
CREATE INDEX idx_inscriptions_category ON athlete_inscriptions (categorycode_id);
CREATE INDEX idx_inscriptions_competition ON athlete_inscriptions (competition_id);
CREATE INDEX idx_rankings_competition ON competition_club_rankings (competition_id);
CREATE INDEX idx_results_panel_category ON results_judged_panel (categorycode_id);
CREATE INDEX idx_results_match_category ON results_match (categorycode_id);
CREATE INDEX idx_results_timed_category ON results_timed (categorycode_id);
CREATE INDEX idx_scores_category ON scores (categorycode_id);
CREATE INDEX idx_tatami_category ON tatami_assignments (categorycode_id);
CREATE INDEX idx_tatami_user ON tatami_assignments (user_id);

CREATE FUNCTION set_modified_date() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    NEW.modified_date = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

CREATE TRIGGER athletes_modified_date BEFORE UPDATE ON athletes
FOR EACH ROW EXECUTE FUNCTION set_modified_date();
CREATE TRIGGER athlete_inscriptions_modified_date BEFORE UPDATE ON athlete_inscriptions
FOR EACH ROW EXECUTE FUNCTION set_modified_date();
CREATE TRIGGER clubs_modified_date BEFORE UPDATE ON clubs
FOR EACH ROW EXECUTE FUNCTION set_modified_date();
CREATE TRIGGER teams_modified_date BEFORE UPDATE ON teams
FOR EACH ROW EXECUTE FUNCTION set_modified_date();

COMMIT;
